version: "3"
services:
  web:
    image: andreas131989/workshops:swarmdemo
    deploy:
      replicas: 5
      restart_policy:
        condition: any
    ports:
      - "80:80"
    networks:
      - webnet

  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    networks:
      - webnet
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  webnet:
